"""Multiplayer

Revision ID: 5f16e2a8ffcb
Revises: 987dfddfd64f
Create Date: 2025-12-10 11:54:11.497967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f16e2a8ffcb'
down_revision: Union[str, Sequence[str], None] = '987dfddfd64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.Enum('VS_COMPUTER', 'VS_PLAYER', name='gametype'), nullable=True))
        batch_op.add_column(sa.Column('game_status', sa.Enum('WAITING', 'PLAYING', 'FINISHED', name='gamestatus'), nullable=True))
        batch_op.add_column(sa.Column('player_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player_o', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_player_o_users'), 'users', ['player_o'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_games_player_x_users'), 'users', ['player_x'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_player_x_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_games_player_o_users'), type_='foreignkey')
        batch_op.drop_column('player_o')
        batch_op.drop_column('player_x')
        batch_op.drop_column('game_status')
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###
